tasks:
  - init: ssh-keygen -t rsa -q -f "test_rsa" -N "" && make test && make build OS=linux ARCH=amd64 && cp dist/venom.linux-amd64 tests/venom && cd tests && make start-test-stack && sleep 10 && make build-test-binary-docker
    command: make run-test
    