tasks:
  - init: |-
      ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N "" && \
      wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
      sudo tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/ && \
      sudo ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/ && \
      phantomjs --version && \
      make test && \
      make build OS=linux ARCH=amd64 && \
      cp dist/venom.linux-amd64 tests/venom && \
      cd tests && \
      make start-test-stack && sleep 10 && \
      make build-test-binary-docker
    command: make run-test
    