// Package avro additional to autogenerated code to read/write from/to
// Kafka structures
package avro

import (
	"github.com/Shopify/sarama"
)

// FromKafka initializes a Message from an input sarama Message
// should be called after NewMessage()
func (k *Message) FromKafka(msg *sarama.ConsumerMessage) error {
	k.Value = make([]byte, len(msg.Value))
	copy(k.Value, msg.Value)
	k.Key = make([]byte, len(msg.Key))
	copy(k.Key, msg.Key)
	k.Timestamp = msg.Timestamp.Unix()
	k.Topic = msg.Topic
	k.Partition = msg.Partition
	k.Offset = msg.Offset
	if len(msg.Headers) == 0 {
		return nil
	}
	k.Headers = make([]*Header, len(msg.Headers))
	for i, header := range msg.Headers {
		k.Headers[i] = NewHeader()
		k.Headers[i].Key = make([]byte, len(header.Key))
		copy(k.Headers[i].Key, header.Key)
		k.Headers[i].Value = make([]byte, len(header.Value))
		copy(k.Headers[i].Value, header.Value)
	}
	return nil
}
