name: Build and Release

# Trigger the workflow on push of a new tag
on:
  push:
    tags:
      - 'v*'  # Matches tags starting with 'v', e.g., v1.0.0
  workflow_dispatch:
    inputs:
      test:
        description: 'test'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: true  # Caches Go modules

      - name: Build Project
        run: |
          make build 

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload binary1 to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          tag: ${{ github.sha }}