name: Build and Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      release_version: ${{ steps.outputs.outputs.release_version }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Build using Makefile
        run: make build

      - name: Create GitHub Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # Dynamically use the tag that triggered the workflow
          name: Release ${{ github.ref_name }}  # Set release name based on the tag
          overwrite: true  # Allows overwriting an existing release if needed
          draft: false
          prerelease: false
          generateReleaseNotes: true
          files: dist/*