name: Build and Release

# Trigger the workflow on push of a new tag
on:
  push:
    tags:
      - 'v*'  # Matches tags starting with 'v', e.g., v1.0.0
  workflow_dispatch:
    inputs:
      test:
        description: 'test'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      release_version: ${{ steps.outputs.outputs.release_version }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Build using Makefile
        run: make build

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v0.0.1'
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generateReleaseNotes: true

      - name: Upload binary1 to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          tag: 'v0.0.1'